include ../makefile_defines.txt

COMPONENT_NAME = m2mconnectionhandlerpimpl_classic_unit
SRC_FILES = \
        ../../../../source/m2mconnectionhandlerpimpl.cpp \

TEST_SRC_FILES = \
        main.cpp \
        m2mconnectionhandlerpimpl_classic_test.cpp \
        test_m2mconnectionhandlerpimpl_classic.cpp \
       ../stub/m2msecurity_stub.cpp \
       ../stub/m2mconnectionsecurity_stub.cpp \
       ../stub/m2mstring_stub.cpp \
       ../stub/m2mobject_stub.cpp \
       ../stub/m2mresource_stub.cpp \
       ../stub/m2mresourceinstance_stub.cpp \
       ../stub/m2mbase_stub.cpp \
       ../stub/m2mconnectionsecurity_stub.cpp \
       ../stub/pal_network_stub.cpp \
       ../stub/eventOS_stub.cpp \
       ../stub/m2mstringbufferbase_stub.cpp \
       ../stub/nsdlaccesshelper_stub.cpp \
       ../stub/pal_stub.cpp \



include ../MakefileWorker.mk

