include ../makefile_defines.txt

COMPONENT_NAME = m2mtimer_classic_unit
SRC_FILES = \
        ../../../../source/m2mtimer.cpp

TEST_SRC_FILES = \
	main.cpp \
        m2mtimertest.cpp \
        test_m2mtimer.cpp \
        ../stub/m2mtimerpimpl_stub.cpp \

include ../MakefileWorker.mk
